### ISSUE TITLE
esp32: task priorities

### ISSUE THREAD

**Issue by atanisoft** [bakerstu/openmrn#212]
Currently the default task level is set to ESP_TASK_TCPIP_PRIO (https://github.com/espressif/esp-idf/blob/master/components/esp32/include/esp_task.h#L53) and this is leveraged for HW CAN RX and TX tasks. We need to explore if we can lower the priorities of these tasks and if so, what makes sense on the ESP32. We need to balance performance and usability.

**Comment by balazsracz** [comment]
We are no longer reliant on separate tasks for TX and RX of CAN packets. The CAN / TWAI driver supports both select-based and async processing APIs.
