### ISSUE TITLE
Esp32: node reboot from jmri doesn't reboot the node

### ISSUE THREAD

**Issue by atanisoft** [bakerstu/openmrn#244]
When in the CDI pane for an esp32 node clicking more then reboot does nothing.

Most likely this just needs a platform specific hook to be put in place but I'm unsure where exactly to put it.

**Comment by balazsracz** [comment]
This is done by an extern "C" function called `reboot()`
https://github.com/bakerstu/openmrn/blob/master/boards/ti-bracz-acc3/HwInit.cxx#L111

**Comment by balazsracz** [comment]
If there is a standard arduino call to reboot the MCU, then we could put that function into OpenMRNLite.cpp.

**Comment by atanisoft** [comment]
I'm not aware of a generic reboot function for all Arduino platforms, on the ESP32 it can be done through a couple approaches: ESP.restart() or esp_restart() (IDF). I'm leaning towards the IDF function since that is what the ESP.restart() calls and we would avoid an include of Arduino.h.

**Comment by balazsracz** [comment]
sounds like it needs to be conditionally compiled for the esp32 then.
I don't see a problem in including Arduino.h into OpenMRNLite.cpp. That does not poison anybody's namespace.

**Comment by atanisoft** [comment]
will namespace play any factor for the C function?

**Comment by balazsracz** [comment]
instead of a namespace you have to wrap it in `extern "C" {` like here:
https://github.com/bakerstu/openmrn/blob/master/boards/ti-bracz-acc3/HwInit.cxx#L89

**Comment by atanisoft** [comment]
Spotted the need for the extern "C" block and tested within the openmrn_arduino namespace and it works as expected now. See PR #247.
