### ISSUE TITLE
Doxygen output does not display on MAC OSx

### ISSUE THREAD

**Issue by JohnFFlanagan** [bakerstu/openmrn#332]
I build the doxygen output some months ago on Mac OSx and nothing really displayed from index.html.  I ignored it but tried again today with updated everything.  Still noting displays but the header, main page tab, Open Model Railroad banner.  And that is all.  I tried Firefox, Google and the native browsers.  

Debug.txt contains
QDir::readDirEntries: Cannot read the directory: /Users/johnSMac/openmrn/applications/async_blink/targets/microchip-pic32mx-generic/misc
QDir::readDirEntries: Cannot read the directory: /Users/johnSMac/openmrn/applications/blink_raw/targets/microchip-pic32mx-generic/misc

and they don't exist.  Nothing starting with microchip does.
index.html (converted to .txt just to upload)
[index.txt](https://github.com/bakerstu/openmrn/files/3794644/index.txt)

**Comment by bakerstu** [comment]
The Doxygen based documentation is known to have rotted and needs updating. It has been on our “todo” list for some time.

**Comment by JohnFFlanagan** [comment]
I spent some time and found an issue, the one that blocked me getting any output.  In the Mac OSx Doxygen version 1.8.16 a "blank" FILE_PATTERNS does not work It needs to be commented out.  I.e.

FILE_PATTERNS       =
to
# FILE_PATTERNS    =
Note spacing is not really correct.

This seems like a Doxygen bug to me.  That said, it my have to be fixed in this code for now.

Once you comment on this comment I will close this.

Thanks .  John

**Comment by balazsracz** [comment]
@JohnFFlanagan would you like to send us a PR with this fix?

**Comment by JohnFFlanagan** [comment]
I spent some time doing both searches and builds.  doxygen 1.8.13, which UBUNTU uses with apt-get works correctly.  1.8.16 which I downloaded as the current stable via the gz file fails.  It appears the not yet released will fix this and in fact building from the current bleeding edge source works correctly.  So I don't know if we should change the Doxyfile to make this work or wait for the correct fix in doxygen.   What are your thoughts?

**Comment by balazsracz** [comment]
If there is a small change we can do to our settings that has no detrimental effect but expands compatibility backwards, we should totally do that.

**Comment by rilull** [comment]
John,
Would you confirm if this issue is fixed? I see a commit into master for it so would like to confirm with you and if so, ask you to mark this as resolved. Thanks!

**Comment by JohnFFlanagan** [comment]
Looks great.  Thanks

**Comment by JohnFFlanagan** [comment]
My bad, I didn't know I had to do that.  I closed it.
Next time I will know.
Sorry
John
