### ISSUE TITLE
Event state handling: state of consumed events is not updated; states can get out of sync.

### ISSUE THREAD

**Issue by balazsracz** [bakerstu/openmrn#4]
There is a provision in the event codebase for keeping the state of produced and consumed events.

This state is initialized during the call to 
    nmranet_event_consumer(node, 0x05020102a8650012ULL, EVENT_STATE_INVALID);
    nmranet_event_producer(node, 0x0502010202000000ULL, EVENT_STATE_INVALID);

The state is sent out in response to producer_identify and consumer_identify commands.

For events produced, the produce call will update the state as it is remembered in the node's events_produced list.

There are a bunch of problems however:

1) For events consumed, the initial state is never changed in the program. This means that with whatever initial state an event was entered, that state will be sent out to the bus every time a consumer_identify message is sent.

2) Also if a node both produces and consumes an event, the states can get out of sync. 

3) If there are multiple virtual nodes, the produced and consumed states of the same event can be arbitrarily out of sync there.

4) There is no user-facing API to query the last state of events.

5) There should be an API to set the state of consumed events, too. For example if there is a pair of events setting/clearing a bit, that should be possible to be reflected in the internal states of OpenMRN.

6) I think the linear search for eventIDs that are assigned to virtual nodes could turn into a problem of efficiency in the case there is a larger number of events being listened to.
For example I am planning to create cue nodes which will be listening to hundreds of events.

**Comment by bakerstu** [comment]
The fundamental architecture has changed. This issue is no longer relevant.
