### ISSUE TITLE
Possibly revisit threading model

### ISSUE THREAD

**Issue by balazsracz** [bakerstu/openmrn#5]
I have been trying to add various features to OpenMRN and I am repeatedly running into issues around the threading model. It basically boils down to needing to start a large number of threads.

Examples:
1) If I were to have multiple virtual nodes, I would need a separate processing thread for each of them.

2) Every physical device needs its own reading thread. can0, can1, uart, usbserial, just to name a few. 
Device driver writing is rather complicated in order to avoid needing a separate TX thread, but it seems that can be done.

3a) Every virtual device will need a thread of its own.
For example if I create a pipe (a virtual loopback device) for exposing a /dev/stdout to the program that takes the characters written there [use-case: debug] and sends them off through some physical device (my candidate would be usb-serial, but a CAN-based logger would do as well). 

3b) other example for virtual devices is the virtual CAN devices.
Let's take the example that we want to connect multiple independent functions of code to the same CAN device. Each function needs to process all CAN packets that come in through the physical link, and any packet generated by any virtual node will need to be sent to all other virtual nodes as well as the physical link.
The use-case for this is to create a CAN-USB implementation that lives in the OpenMRN node but looks like a gridconnect interface to the host.
Another example is that I have a piece of code that drives a CANbus-connected throttle that speaks a legacy protocol. This would need to be running on a virtual device, since OpenMRN does not expose an API to the application for processing unknown CAN packets.
Such a virtual CAN device could be implemented very nicely using the file abstraction. However, that would need for N virtual devices an additional N threads (next to the already existing N threads that the various components are running in order to read).

So it seems to me that a set of functionality that I had previously packed into a 8-bit PIC with 4K of RAM (quite comfortably) suddenly needs something like 15 threads running.

**Comment by bakerstu** [comment]
The fundamental architecture has changed. This issue is no longer relevant.
