### ISSUE TITLE
POM CV writes interpret railcom returns incorrectly

### ISSUE THREAD

**Issue by balazsracz** [bakerstu/openmrn#517]
in the openlcb/*CVSpace.cxx we interpret the returned railcom feedback. The code there is not compliant to the standard.
Specifically, a write is only acknowledged as done by the decoder when it sends back a readout of the same CV. Sending back an ACK is not a positive acknowledgement of a successful write according to the standard.

**Comment by atanisoft** [comment]
@balazsracz was this fixed as part of PR https://github.com/bakerstu/openmrn/pull/560?

**Comment by balazsracz** [comment]
Fixed by #560.
