### ISSUE TITLE
Possible future compiler problem with MultiConfiguredPC.hxx: std::allocator::construct & std::allocator::destroy going away

### ISSUE THREAD

**Issue by RobertPHeller** [bakerstu/openmrn#711]
When compiling with -std=gnu++20 (the default for ESP-IDF-V5.0.1), MultiConfiguredPC.hxx gets (fatal) compiler errors involving the use of std::allocator::construct & std::allocator::destroy.  Not a problem now if -std=gnu++14, but will probably be a problem someday...

**Comment by bakerstu** [comment]
As a general note, we don't typically like to use the "gnu" language version options. "gnu" tends to pull in components that may be experimental and/or not portable to other non GCC compilers, which we also support. So we prefer -std=c++14 rather than -std=gnu++14.

**Comment by atanisoft** [comment]
@bakerstu Unless things have changed, ESP-IDF depends on a few GNU extensions. ESP-IDF defaults to using whichever of these works first: gnu++20 gnu++2a gnu++17 gnu++14
