### ISSUE TITLE
Usability problem with events API

### ISSUE THREAD

**Issue by balazsracz** [bakerstu/openmrn#8]
There are two calls with the same prototype and the name just differing in one character:
void nmranet_event_producer(node_t node, uint64_t event, unsigned int state);
void nmranet_event_produce(node_t node, uint64_t event, unsigned int state);

But there is a major difference in where and how to use them. This very easily leads to bugs on the application side.

I recommend renaming the former call to
register_nmranet_event_producer(...)
and similarly the register consumer call for consistency (although there the API confusion does not hold).

**Comment by bakerstu** [comment]
The fundamental architecture has changed. This issue is no longer relevant.
